spring:
  pid:
    fail-on-write-error: true
    file: kobalttown.pid
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    prefix: 'file:front/templates/'
    suffix: '.html'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    idle-timeout: 12000
    connection-test-query: SELECT 1
  jpa:
    database: mysql
    open-in-view: false
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} - %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%logger#%M [L.%L]){cyan} %clr(:){faint} %m%n%wEx'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} --- %p --- [%t] %logger --- %m%n%wEx'
  level:
    root: warn
    kr.lul.kobalttown.support.spring: info